### ISSUE TITLE
Error: Cannot find module './config.json'

### ISSUE THREAD

**Issue by windowsoffender** [DeadPackets/CRNotify#91] opened 2024-08-24 22:30 UTC
I need a config.json but you gitignored yousssef. Please I need to run this mr ad lab 

Regards,
ad lab
![68747470733a2f2f692e696d6775722e636f6d2f436830526e67632e706e67](https://github.com/user-attachments/assets/99f49488-db5d-410e-8288-65d9855d046c)
![9aose861nxo31](https://github.com/user-attachments/assets/607cffc8-ff4e-4686-a95a-3d3adda0b50f)

**Comment by DeadPackets** [comment] 2024-08-26 16:06
Duplicate of #1

**Closed as completed** 2024-08-26 16:06 UTC
